#!/usr/bin/env bash
# script which creates a file and saves its PID inside
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill command" on  receiving SIGTERM
# displays "Y U no love me?!" onreceiving SIGINT
# deletes the file and terminates itself on revevbing SIGQUIT or SIGTERM

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
echo 'To infinity and beyond'
sleep 2
trap 'echo "I hate the kill command" ; sudo rm /var/run/myscript.pid; exit' 15
trap 'echo "Y U no love me?!"' 2
trap 'sudo rm /var/run/myscript.pid; exit' 3
done
